# Generated by Django 2.2.1 on 2020-03-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='用户名/手机号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='', max_length=32, verbose_name='性别')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='地址')),
                ('image', models.ImageField(default='static/image/default.jpg', max_length=128, upload_to='static/image/%Y/%m')),
            ],
            options={
                'verbose_name': '用户基本信息表',
                'verbose_name_plural': '用户基本信息表',
                'db_table': 'user',
            },
        ),
    ]
