# Generated by Django 2.2.1 on 2020-03-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200303_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=11, unique=True, verbose_name='用户名/手机号'),
        ),
    ]
