# Generated by Django 2.2.1 on 2020-03-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='course',
            new_name='courses',
        ),
    ]
