# Generated by Django 2.2.1 on 2020-03-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200329_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.jpg', max_length=128, upload_to='image/%Y/%m'),
        ),
    ]
