# Generated by Django 2.2.1 on 2020-03-08 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='课程名称')),
                ('desc', models.CharField(max_length=256, verbose_name='课程描述')),
                ('detail', models.TextField(max_length=255, verbose_name='课程详情')),
                ('degree', models.CharField(max_length=5, verbose_name='课程等级')),
                ('learn_time', models.IntegerField(default=0, verbose_name='课程时长')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击人数')),
                ('image', models.CharField(max_length=255, verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
                'db_table': 'course',
            },
        ),
    ]
