# Generated by Django 2.2.1 on 2020-03-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_2',
            field=models.CharField(default='', max_length=255, verbose_name='小图片'),
        ),
    ]
