# Generated by Django 2.2.1 on 2020-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_video_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(default='www.baidu.com', max_length=500, verbose_name='访问地址'),
        ),
    ]
