# Generated by Django 2.2.1 on 2020-04-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20200330_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freeback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='反馈标题')),
                ('detail', models.CharField(max_length=1000, verbose_name='反馈内容')),
            ],
            options={
                'verbose_name': '反馈',
                'verbose_name_plural': '反馈',
                'db_table': 'freeback',
            },
        ),
    ]
